// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zigchain/factory/denom_auth.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DenomAuth is a struct that contains the bank and metadata admin of a denom
type DenomAuth struct {
	Denom         string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	BankAdmin     string `protobuf:"bytes,2,opt,name=bank_admin,json=bankAdmin,proto3" json:"bank_admin,omitempty"`
	MetadataAdmin string `protobuf:"bytes,3,opt,name=metadata_admin,json=metadataAdmin,proto3" json:"metadata_admin,omitempty"`
}

func (m *DenomAuth) Reset()         { *m = DenomAuth{} }
func (m *DenomAuth) String() string { return proto.CompactTextString(m) }
func (*DenomAuth) ProtoMessage()    {}
func (*DenomAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_c86370a6a484d4da, []int{0}
}
func (m *DenomAuth) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomAuth.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomAuth.Merge(m, src)
}
func (m *DenomAuth) XXX_Size() int {
	return m.Size()
}
func (m *DenomAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomAuth.DiscardUnknown(m)
}

var xxx_messageInfo_DenomAuth proto.InternalMessageInfo

func (m *DenomAuth) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomAuth) GetBankAdmin() string {
	if m != nil {
		return m.BankAdmin
	}
	return ""
}

func (m *DenomAuth) GetMetadataAdmin() string {
	if m != nil {
		return m.MetadataAdmin
	}
	return ""
}

func init() {
	proto.RegisterType((*DenomAuth)(nil), "zigchain.factory.DenomAuth")
}

func init() { proto.RegisterFile("zigchain/factory/denom_auth.proto", fileDescriptor_c86370a6a484d4da) }

var fileDescriptor_c86370a6a484d4da = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xac, 0xca, 0x4c, 0x4f,
	0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0x4b, 0x4c, 0x2e, 0xc9, 0x2f, 0xaa, 0xd4, 0x4f, 0x49, 0xcd,
	0xcb, 0xcf, 0x8d, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80,
	0x29, 0xd1, 0x83, 0x2a, 0x51, 0x4a, 0xe7, 0xe2, 0x74, 0x01, 0xa9, 0x72, 0x2c, 0x2d, 0xc9, 0x10,
	0x12, 0xe1, 0x62, 0x05, 0x6b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x64,
	0xb9, 0xb8, 0x92, 0x12, 0xf3, 0xb2, 0xe3, 0x13, 0x53, 0x72, 0x33, 0xf3, 0x24, 0x98, 0xc0, 0x52,
	0x9c, 0x20, 0x11, 0x47, 0x90, 0x80, 0x90, 0x2a, 0x17, 0x5f, 0x6e, 0x6a, 0x49, 0x62, 0x4a, 0x62,
	0x49, 0x22, 0x54, 0x09, 0x33, 0x58, 0x09, 0x2f, 0x4c, 0x14, 0xac, 0xcc, 0xc9, 0xe8, 0xc4, 0x23,
	0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2,
	0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x24, 0xe0, 0xee, 0xae, 0x80, 0xbb, 0xbc, 0xa4,
	0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x6a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7,
	0xfc, 0x84, 0x53, 0xda, 0x00, 0x00, 0x00,
}

func (m *DenomAuth) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomAuth) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomAuth) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataAdmin) > 0 {
		i -= len(m.MetadataAdmin)
		copy(dAtA[i:], m.MetadataAdmin)
		i = encodeVarintDenomAuth(dAtA, i, uint64(len(m.MetadataAdmin)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BankAdmin) > 0 {
		i -= len(m.BankAdmin)
		copy(dAtA[i:], m.BankAdmin)
		i = encodeVarintDenomAuth(dAtA, i, uint64(len(m.BankAdmin)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintDenomAuth(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDenomAuth(dAtA []byte, offset int, v uint64) int {
	offset -= sovDenomAuth(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DenomAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovDenomAuth(uint64(l))
	}
	l = len(m.BankAdmin)
	if l > 0 {
		n += 1 + l + sovDenomAuth(uint64(l))
	}
	l = len(m.MetadataAdmin)
	if l > 0 {
		n += 1 + l + sovDenomAuth(uint64(l))
	}
	return n
}

func sovDenomAuth(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDenomAuth(x uint64) (n int) {
	return sovDenomAuth(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DenomAuth) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDenomAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomAuth: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomAuth: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenomAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDenomAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDenomAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BankAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenomAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDenomAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDenomAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BankAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenomAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDenomAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDenomAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDenomAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDenomAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDenomAuth(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDenomAuth
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDenomAuth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDenomAuth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDenomAuth
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDenomAuth
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDenomAuth
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDenomAuth        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDenomAuth          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDenomAuth = fmt.Errorf("proto: unexpected end of group")
)
