// Code generated by MockGen. DO NOT EDIT.
// Source: x/tokenwrapper/types/expected_ibc_keeper.go
//
// Generated by this command:
//
//	mockgen -source=x/tokenwrapper/types/expected_ibc_keeper.go -package testutil -destination x/tokenwrapper/testutil/expected_ibc_keeper_mocks.go
//

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	log "cosmossdk.io/log"
	math "cosmossdk.io/math"
	types "github.com/cosmos/cosmos-sdk/types"
	types0 "github.com/cosmos/ibc-go/v10/modules/core/02-client/types"
	types1 "github.com/cosmos/ibc-go/v10/modules/core/03-connection/types"
	types2 "github.com/cosmos/ibc-go/v10/modules/core/04-channel/types"
	exported "github.com/cosmos/ibc-go/v10/modules/core/exported"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelKeeper is a mock of ChannelKeeper interface.
type MockChannelKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockChannelKeeperMockRecorder
	isgomock struct{}
}

// MockChannelKeeperMockRecorder is the mock recorder for MockChannelKeeper.
type MockChannelKeeperMockRecorder struct {
	mock *MockChannelKeeper
}

// NewMockChannelKeeper creates a new mock instance.
func NewMockChannelKeeper(ctrl *gomock.Controller) *MockChannelKeeper {
	mock := &MockChannelKeeper{ctrl: ctrl}
	mock.recorder = &MockChannelKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelKeeper) EXPECT() *MockChannelKeeperMockRecorder {
	return m.recorder
}

// GetChannel mocks base method.
func (m *MockChannelKeeper) GetChannel(ctx types.Context, portID, channelID string) (types2.Channel, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, portID, channelID)
	ret0, _ := ret[0].(types2.Channel)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockChannelKeeperMockRecorder) GetChannel(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockChannelKeeper)(nil).GetChannel), ctx, portID, channelID)
}

// MockConnectionKeeper is a mock of ConnectionKeeper interface.
type MockConnectionKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionKeeperMockRecorder
	isgomock struct{}
}

// MockConnectionKeeperMockRecorder is the mock recorder for MockConnectionKeeper.
type MockConnectionKeeperMockRecorder struct {
	mock *MockConnectionKeeper
}

// NewMockConnectionKeeper creates a new mock instance.
func NewMockConnectionKeeper(ctrl *gomock.Controller) *MockConnectionKeeper {
	mock := &MockConnectionKeeper{ctrl: ctrl}
	mock.recorder = &MockConnectionKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionKeeper) EXPECT() *MockConnectionKeeperMockRecorder {
	return m.recorder
}

// GetConnection mocks base method.
func (m *MockConnectionKeeper) GetConnection(ctx types.Context, connectionID string) (types1.ConnectionEnd, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, connectionID)
	ret0, _ := ret[0].(types1.ConnectionEnd)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockConnectionKeeperMockRecorder) GetConnection(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockConnectionKeeper)(nil).GetConnection), ctx, connectionID)
}

// MockTransferKeeper is a mock of TransferKeeper interface.
type MockTransferKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockTransferKeeperMockRecorder
	isgomock struct{}
}

// MockTransferKeeperMockRecorder is the mock recorder for MockTransferKeeper.
type MockTransferKeeperMockRecorder struct {
	mock *MockTransferKeeper
}

// NewMockTransferKeeper creates a new mock instance.
func NewMockTransferKeeper(ctrl *gomock.Controller) *MockTransferKeeper {
	mock := &MockTransferKeeper{ctrl: ctrl}
	mock.recorder = &MockTransferKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferKeeper) EXPECT() *MockTransferKeeperMockRecorder {
	return m.recorder
}

// GetTotalEscrowForDenom mocks base method.
func (m *MockTransferKeeper) GetTotalEscrowForDenom(ctx types.Context, denom string) types.Coin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalEscrowForDenom", ctx, denom)
	ret0, _ := ret[0].(types.Coin)
	return ret0
}

// GetTotalEscrowForDenom indicates an expected call of GetTotalEscrowForDenom.
func (mr *MockTransferKeeperMockRecorder) GetTotalEscrowForDenom(ctx, denom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalEscrowForDenom", reflect.TypeOf((*MockTransferKeeper)(nil).GetTotalEscrowForDenom), ctx, denom)
}

// SetTotalEscrowForDenom mocks base method.
func (m *MockTransferKeeper) SetTotalEscrowForDenom(ctx types.Context, coin types.Coin) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTotalEscrowForDenom", ctx, coin)
}

// SetTotalEscrowForDenom indicates an expected call of SetTotalEscrowForDenom.
func (mr *MockTransferKeeperMockRecorder) SetTotalEscrowForDenom(ctx, coin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTotalEscrowForDenom", reflect.TypeOf((*MockTransferKeeper)(nil).SetTotalEscrowForDenom), ctx, coin)
}

// MockCallbacksCompatibleModule is a mock of CallbacksCompatibleModule interface.
type MockCallbacksCompatibleModule struct {
	ctrl     *gomock.Controller
	recorder *MockCallbacksCompatibleModuleMockRecorder
	isgomock struct{}
}

// MockCallbacksCompatibleModuleMockRecorder is the mock recorder for MockCallbacksCompatibleModule.
type MockCallbacksCompatibleModuleMockRecorder struct {
	mock *MockCallbacksCompatibleModule
}

// NewMockCallbacksCompatibleModule creates a new mock instance.
func NewMockCallbacksCompatibleModule(ctrl *gomock.Controller) *MockCallbacksCompatibleModule {
	mock := &MockCallbacksCompatibleModule{ctrl: ctrl}
	mock.recorder = &MockCallbacksCompatibleModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallbacksCompatibleModule) EXPECT() *MockCallbacksCompatibleModuleMockRecorder {
	return m.recorder
}

// OnAcknowledgementPacket mocks base method.
func (m *MockCallbacksCompatibleModule) OnAcknowledgementPacket(ctx types.Context, channelVersion string, packet types2.Packet, acknowledgement []byte, relayer types.AccAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnAcknowledgementPacket", ctx, channelVersion, packet, acknowledgement, relayer)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnAcknowledgementPacket indicates an expected call of OnAcknowledgementPacket.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnAcknowledgementPacket(ctx, channelVersion, packet, acknowledgement, relayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAcknowledgementPacket", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnAcknowledgementPacket), ctx, channelVersion, packet, acknowledgement, relayer)
}

// OnChanCloseConfirm mocks base method.
func (m *MockCallbacksCompatibleModule) OnChanCloseConfirm(ctx types.Context, portID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanCloseConfirm", ctx, portID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanCloseConfirm indicates an expected call of OnChanCloseConfirm.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnChanCloseConfirm(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanCloseConfirm", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnChanCloseConfirm), ctx, portID, channelID)
}

// OnChanCloseInit mocks base method.
func (m *MockCallbacksCompatibleModule) OnChanCloseInit(ctx types.Context, portID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanCloseInit", ctx, portID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanCloseInit indicates an expected call of OnChanCloseInit.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnChanCloseInit(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanCloseInit", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnChanCloseInit), ctx, portID, channelID)
}

// OnChanOpenAck mocks base method.
func (m *MockCallbacksCompatibleModule) OnChanOpenAck(ctx types.Context, portID, channelID, counterpartyChannelID, counterpartyVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenAck", ctx, portID, channelID, counterpartyChannelID, counterpartyVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanOpenAck indicates an expected call of OnChanOpenAck.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnChanOpenAck(ctx, portID, channelID, counterpartyChannelID, counterpartyVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenAck", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnChanOpenAck), ctx, portID, channelID, counterpartyChannelID, counterpartyVersion)
}

// OnChanOpenConfirm mocks base method.
func (m *MockCallbacksCompatibleModule) OnChanOpenConfirm(ctx types.Context, portID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenConfirm", ctx, portID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanOpenConfirm indicates an expected call of OnChanOpenConfirm.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnChanOpenConfirm(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenConfirm", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnChanOpenConfirm), ctx, portID, channelID)
}

// OnChanOpenInit mocks base method.
func (m *MockCallbacksCompatibleModule) OnChanOpenInit(ctx types.Context, order types2.Order, connectionHops []string, portID, channelID string, counterparty types2.Counterparty, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenInit", ctx, order, connectionHops, portID, channelID, counterparty, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnChanOpenInit indicates an expected call of OnChanOpenInit.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnChanOpenInit(ctx, order, connectionHops, portID, channelID, counterparty, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenInit", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnChanOpenInit), ctx, order, connectionHops, portID, channelID, counterparty, version)
}

// OnChanOpenTry mocks base method.
func (m *MockCallbacksCompatibleModule) OnChanOpenTry(ctx types.Context, order types2.Order, connectionHops []string, portID, channelID string, counterparty types2.Counterparty, counterpartyVersion string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenTry", ctx, order, connectionHops, portID, channelID, counterparty, counterpartyVersion)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnChanOpenTry indicates an expected call of OnChanOpenTry.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnChanOpenTry(ctx, order, connectionHops, portID, channelID, counterparty, counterpartyVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenTry", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnChanOpenTry), ctx, order, connectionHops, portID, channelID, counterparty, counterpartyVersion)
}

// OnRecvPacket mocks base method.
func (m *MockCallbacksCompatibleModule) OnRecvPacket(ctx types.Context, channelVersion string, packet types2.Packet, relayer types.AccAddress) exported.Acknowledgement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnRecvPacket", ctx, channelVersion, packet, relayer)
	ret0, _ := ret[0].(exported.Acknowledgement)
	return ret0
}

// OnRecvPacket indicates an expected call of OnRecvPacket.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnRecvPacket(ctx, channelVersion, packet, relayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRecvPacket", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnRecvPacket), ctx, channelVersion, packet, relayer)
}

// OnTimeoutPacket mocks base method.
func (m *MockCallbacksCompatibleModule) OnTimeoutPacket(ctx types.Context, channelVersion string, packet types2.Packet, relayer types.AccAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTimeoutPacket", ctx, channelVersion, packet, relayer)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnTimeoutPacket indicates an expected call of OnTimeoutPacket.
func (mr *MockCallbacksCompatibleModuleMockRecorder) OnTimeoutPacket(ctx, channelVersion, packet, relayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTimeoutPacket", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).OnTimeoutPacket), ctx, channelVersion, packet, relayer)
}

// UnmarshalPacketData mocks base method.
func (m *MockCallbacksCompatibleModule) UnmarshalPacketData(ctx types.Context, portID, channelID string, bz []byte) (any, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalPacketData", ctx, portID, channelID, bz)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UnmarshalPacketData indicates an expected call of UnmarshalPacketData.
func (mr *MockCallbacksCompatibleModuleMockRecorder) UnmarshalPacketData(ctx, portID, channelID, bz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalPacketData", reflect.TypeOf((*MockCallbacksCompatibleModule)(nil).UnmarshalPacketData), ctx, portID, channelID, bz)
}

// MockICS4Wrapper is a mock of ICS4Wrapper interface.
type MockICS4Wrapper struct {
	ctrl     *gomock.Controller
	recorder *MockICS4WrapperMockRecorder
	isgomock struct{}
}

// MockICS4WrapperMockRecorder is the mock recorder for MockICS4Wrapper.
type MockICS4WrapperMockRecorder struct {
	mock *MockICS4Wrapper
}

// NewMockICS4Wrapper creates a new mock instance.
func NewMockICS4Wrapper(ctrl *gomock.Controller) *MockICS4Wrapper {
	mock := &MockICS4Wrapper{ctrl: ctrl}
	mock.recorder = &MockICS4WrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICS4Wrapper) EXPECT() *MockICS4WrapperMockRecorder {
	return m.recorder
}

// GetAppVersion mocks base method.
func (m *MockICS4Wrapper) GetAppVersion(ctx types.Context, portID, channelID string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppVersion", ctx, portID, channelID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetAppVersion indicates an expected call of GetAppVersion.
func (mr *MockICS4WrapperMockRecorder) GetAppVersion(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppVersion", reflect.TypeOf((*MockICS4Wrapper)(nil).GetAppVersion), ctx, portID, channelID)
}

// SendPacket mocks base method.
func (m *MockICS4Wrapper) SendPacket(ctx types.Context, sourcePort, sourceChannel string, timeoutHeight types0.Height, timeoutTimestamp uint64, data []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPacket", ctx, sourcePort, sourceChannel, timeoutHeight, timeoutTimestamp, data)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPacket indicates an expected call of SendPacket.
func (mr *MockICS4WrapperMockRecorder) SendPacket(ctx, sourcePort, sourceChannel, timeoutHeight, timeoutTimestamp, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPacket", reflect.TypeOf((*MockICS4Wrapper)(nil).SendPacket), ctx, sourcePort, sourceChannel, timeoutHeight, timeoutTimestamp, data)
}

// WriteAcknowledgement mocks base method.
func (m *MockICS4Wrapper) WriteAcknowledgement(ctx types.Context, packet exported.PacketI, ack exported.Acknowledgement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAcknowledgement", ctx, packet, ack)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAcknowledgement indicates an expected call of WriteAcknowledgement.
func (mr *MockICS4WrapperMockRecorder) WriteAcknowledgement(ctx, packet, ack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAcknowledgement", reflect.TypeOf((*MockICS4Wrapper)(nil).WriteAcknowledgement), ctx, packet, ack)
}

// MockTokenwrapperKeeper is a mock of TokenwrapperKeeper interface.
type MockTokenwrapperKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockTokenwrapperKeeperMockRecorder
	isgomock struct{}
}

// MockTokenwrapperKeeperMockRecorder is the mock recorder for MockTokenwrapperKeeper.
type MockTokenwrapperKeeperMockRecorder struct {
	mock *MockTokenwrapperKeeper
}

// NewMockTokenwrapperKeeper creates a new mock instance.
func NewMockTokenwrapperKeeper(ctrl *gomock.Controller) *MockTokenwrapperKeeper {
	mock := &MockTokenwrapperKeeper{ctrl: ctrl}
	mock.recorder = &MockTokenwrapperKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenwrapperKeeper) EXPECT() *MockTokenwrapperKeeperMockRecorder {
	return m.recorder
}

// AddToTotalTransferredIn mocks base method.
func (m *MockTokenwrapperKeeper) AddToTotalTransferredIn(ctx types.Context, amount math.Int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddToTotalTransferredIn", ctx, amount)
}

// AddToTotalTransferredIn indicates an expected call of AddToTotalTransferredIn.
func (mr *MockTokenwrapperKeeperMockRecorder) AddToTotalTransferredIn(ctx, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToTotalTransferredIn", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).AddToTotalTransferredIn), ctx, amount)
}

// AddToTotalTransferredOut mocks base method.
func (m *MockTokenwrapperKeeper) AddToTotalTransferredOut(ctx types.Context, amount math.Int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddToTotalTransferredOut", ctx, amount)
}

// AddToTotalTransferredOut indicates an expected call of AddToTotalTransferredOut.
func (mr *MockTokenwrapperKeeperMockRecorder) AddToTotalTransferredOut(ctx, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToTotalTransferredOut", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).AddToTotalTransferredOut), ctx, amount)
}

// BurnIbcTokens mocks base method.
func (m *MockTokenwrapperKeeper) BurnIbcTokens(ctx types.Context, amt types.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BurnIbcTokens", ctx, amt)
	ret0, _ := ret[0].(error)
	return ret0
}

// BurnIbcTokens indicates an expected call of BurnIbcTokens.
func (mr *MockTokenwrapperKeeperMockRecorder) BurnIbcTokens(ctx, amt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BurnIbcTokens", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).BurnIbcTokens), ctx, amt)
}

// CheckAccountBalance mocks base method.
func (m *MockTokenwrapperKeeper) CheckAccountBalance(ctx types.Context, addr types.AccAddress, coins types.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccountBalance", ctx, addr, coins)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAccountBalance indicates an expected call of CheckAccountBalance.
func (mr *MockTokenwrapperKeeperMockRecorder) CheckAccountBalance(ctx, addr, coins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccountBalance", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).CheckAccountBalance), ctx, addr, coins)
}

// CheckBalances mocks base method.
func (m *MockTokenwrapperKeeper) CheckBalances(ctx types.Context, receiver types.AccAddress, amount math.Int, recvDenom string, convertedAmount math.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBalances", ctx, receiver, amount, recvDenom, convertedAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckBalances indicates an expected call of CheckBalances.
func (mr *MockTokenwrapperKeeperMockRecorder) CheckBalances(ctx, receiver, amount, recvDenom, convertedAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBalances", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).CheckBalances), ctx, receiver, amount, recvDenom, convertedAmount)
}

// CheckModuleBalance mocks base method.
func (m *MockTokenwrapperKeeper) CheckModuleBalance(ctx types.Context, coins types.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckModuleBalance", ctx, coins)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckModuleBalance indicates an expected call of CheckModuleBalance.
func (mr *MockTokenwrapperKeeperMockRecorder) CheckModuleBalance(ctx, coins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckModuleBalance", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).CheckModuleBalance), ctx, coins)
}

// GetCounterpartyChannel mocks base method.
func (m *MockTokenwrapperKeeper) GetCounterpartyChannel(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterpartyChannel", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCounterpartyChannel indicates an expected call of GetCounterpartyChannel.
func (mr *MockTokenwrapperKeeperMockRecorder) GetCounterpartyChannel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterpartyChannel", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetCounterpartyChannel), ctx)
}

// GetCounterpartyClientId mocks base method.
func (m *MockTokenwrapperKeeper) GetCounterpartyClientId(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterpartyClientId", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCounterpartyClientId indicates an expected call of GetCounterpartyClientId.
func (mr *MockTokenwrapperKeeperMockRecorder) GetCounterpartyClientId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterpartyClientId", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetCounterpartyClientId), ctx)
}

// GetCounterpartyPort mocks base method.
func (m *MockTokenwrapperKeeper) GetCounterpartyPort(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterpartyPort", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCounterpartyPort indicates an expected call of GetCounterpartyPort.
func (mr *MockTokenwrapperKeeperMockRecorder) GetCounterpartyPort(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterpartyPort", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetCounterpartyPort), ctx)
}

// GetDecimalConversionFactor mocks base method.
func (m *MockTokenwrapperKeeper) GetDecimalConversionFactor(ctx types.Context) math.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecimalConversionFactor", ctx)
	ret0, _ := ret[0].(math.Int)
	return ret0
}

// GetDecimalConversionFactor indicates an expected call of GetDecimalConversionFactor.
func (mr *MockTokenwrapperKeeperMockRecorder) GetDecimalConversionFactor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecimalConversionFactor", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetDecimalConversionFactor), ctx)
}

// GetDecimalDifference mocks base method.
func (m *MockTokenwrapperKeeper) GetDecimalDifference(ctx types.Context) uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecimalDifference", ctx)
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetDecimalDifference indicates an expected call of GetDecimalDifference.
func (mr *MockTokenwrapperKeeperMockRecorder) GetDecimalDifference(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecimalDifference", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetDecimalDifference), ctx)
}

// GetDenom mocks base method.
func (m *MockTokenwrapperKeeper) GetDenom(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDenom", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDenom indicates an expected call of GetDenom.
func (mr *MockTokenwrapperKeeperMockRecorder) GetDenom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDenom", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetDenom), ctx)
}

// GetIBCRecvDenom mocks base method.
func (m *MockTokenwrapperKeeper) GetIBCRecvDenom(ctx types.Context, denom string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIBCRecvDenom", ctx, denom)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIBCRecvDenom indicates an expected call of GetIBCRecvDenom.
func (mr *MockTokenwrapperKeeperMockRecorder) GetIBCRecvDenom(ctx, denom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIBCRecvDenom", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetIBCRecvDenom), ctx, denom)
}

// GetNativeChannel mocks base method.
func (m *MockTokenwrapperKeeper) GetNativeChannel(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNativeChannel", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNativeChannel indicates an expected call of GetNativeChannel.
func (mr *MockTokenwrapperKeeperMockRecorder) GetNativeChannel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNativeChannel", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetNativeChannel), ctx)
}

// GetNativeClientId mocks base method.
func (m *MockTokenwrapperKeeper) GetNativeClientId(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNativeClientId", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNativeClientId indicates an expected call of GetNativeClientId.
func (mr *MockTokenwrapperKeeperMockRecorder) GetNativeClientId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNativeClientId", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetNativeClientId), ctx)
}

// GetNativePort mocks base method.
func (m *MockTokenwrapperKeeper) GetNativePort(ctx types.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNativePort", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNativePort indicates an expected call of GetNativePort.
func (mr *MockTokenwrapperKeeperMockRecorder) GetNativePort(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNativePort", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).GetNativePort), ctx)
}

// IsEnabled mocks base method.
func (m *MockTokenwrapperKeeper) IsEnabled(ctx types.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockTokenwrapperKeeperMockRecorder) IsEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).IsEnabled), ctx)
}

// LockIBCTokens mocks base method.
func (m *MockTokenwrapperKeeper) LockIBCTokens(ctx types.Context, receiver types.AccAddress, amount math.Int, recvDenom string) (types.Coins, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockIBCTokens", ctx, receiver, amount, recvDenom)
	ret0, _ := ret[0].(types.Coins)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockIBCTokens indicates an expected call of LockIBCTokens.
func (mr *MockTokenwrapperKeeperMockRecorder) LockIBCTokens(ctx, receiver, amount, recvDenom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockIBCTokens", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).LockIBCTokens), ctx, receiver, amount, recvDenom)
}

// LockTokens mocks base method.
func (m *MockTokenwrapperKeeper) LockTokens(ctx types.Context, addr types.AccAddress, amt types.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockTokens", ctx, addr, amt)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockTokens indicates an expected call of LockTokens.
func (mr *MockTokenwrapperKeeperMockRecorder) LockTokens(ctx, addr, amt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockTokens", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).LockTokens), ctx, addr, amt)
}

// Logger mocks base method.
func (m *MockTokenwrapperKeeper) Logger() log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(log.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockTokenwrapperKeeperMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).Logger))
}

// ScaleDownTokenPrecision mocks base method.
func (m *MockTokenwrapperKeeper) ScaleDownTokenPrecision(ctx types.Context, amount math.Int) (math.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScaleDownTokenPrecision", ctx, amount)
	ret0, _ := ret[0].(math.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScaleDownTokenPrecision indicates an expected call of ScaleDownTokenPrecision.
func (mr *MockTokenwrapperKeeperMockRecorder) ScaleDownTokenPrecision(ctx, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScaleDownTokenPrecision", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).ScaleDownTokenPrecision), ctx, amount)
}

// ScaleUpTokenPrecision mocks base method.
func (m *MockTokenwrapperKeeper) ScaleUpTokenPrecision(ctx types.Context, amount math.Int) (math.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScaleUpTokenPrecision", ctx, amount)
	ret0, _ := ret[0].(math.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScaleUpTokenPrecision indicates an expected call of ScaleUpTokenPrecision.
func (mr *MockTokenwrapperKeeperMockRecorder) ScaleUpTokenPrecision(ctx, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScaleUpTokenPrecision", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).ScaleUpTokenPrecision), ctx, amount)
}

// UnlockNativeTokens mocks base method.
func (m *MockTokenwrapperKeeper) UnlockNativeTokens(ctx types.Context, receiver types.AccAddress, amount math.Int, ibcCoins types.Coins) (types.Coins, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockNativeTokens", ctx, receiver, amount, ibcCoins)
	ret0, _ := ret[0].(types.Coins)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockNativeTokens indicates an expected call of UnlockNativeTokens.
func (mr *MockTokenwrapperKeeperMockRecorder) UnlockNativeTokens(ctx, receiver, amount, ibcCoins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockNativeTokens", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).UnlockNativeTokens), ctx, receiver, amount, ibcCoins)
}

// UnlockTokens mocks base method.
func (m *MockTokenwrapperKeeper) UnlockTokens(ctx types.Context, addr types.AccAddress, amt types.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockTokens", ctx, addr, amt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockTokens indicates an expected call of UnlockTokens.
func (mr *MockTokenwrapperKeeperMockRecorder) UnlockTokens(ctx, addr, amt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTokens", reflect.TypeOf((*MockTokenwrapperKeeper)(nil).UnlockTokens), ctx, addr, amt)
}
