// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package tokenwrapper

import (
	_ "cosmossdk.io/api/amino"
	_ "cosmossdk.io/api/cosmos/base/v1beta1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_PauserAddresses_1_list)(nil)

type _PauserAddresses_1_list struct {
	list *[]string
}

func (x *_PauserAddresses_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_PauserAddresses_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_PauserAddresses_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_PauserAddresses_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_PauserAddresses_1_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message PauserAddresses at list field Addresses as it is not of Message kind"))
}

func (x *_PauserAddresses_1_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_PauserAddresses_1_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_PauserAddresses_1_list) IsValid() bool {
	return x.list != nil
}

var (
	md_PauserAddresses           protoreflect.MessageDescriptor
	fd_PauserAddresses_addresses protoreflect.FieldDescriptor
)

func init() {
	file_zigchain_tokenwrapper_genesis_proto_init()
	md_PauserAddresses = File_zigchain_tokenwrapper_genesis_proto.Messages().ByName("PauserAddresses")
	fd_PauserAddresses_addresses = md_PauserAddresses.Fields().ByName("addresses")
}

var _ protoreflect.Message = (*fastReflection_PauserAddresses)(nil)

type fastReflection_PauserAddresses PauserAddresses

func (x *PauserAddresses) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PauserAddresses)(x)
}

func (x *PauserAddresses) slowProtoReflect() protoreflect.Message {
	mi := &file_zigchain_tokenwrapper_genesis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PauserAddresses_messageType fastReflection_PauserAddresses_messageType
var _ protoreflect.MessageType = fastReflection_PauserAddresses_messageType{}

type fastReflection_PauserAddresses_messageType struct{}

func (x fastReflection_PauserAddresses_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PauserAddresses)(nil)
}
func (x fastReflection_PauserAddresses_messageType) New() protoreflect.Message {
	return new(fastReflection_PauserAddresses)
}
func (x fastReflection_PauserAddresses_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PauserAddresses
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PauserAddresses) Descriptor() protoreflect.MessageDescriptor {
	return md_PauserAddresses
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PauserAddresses) Type() protoreflect.MessageType {
	return _fastReflection_PauserAddresses_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PauserAddresses) New() protoreflect.Message {
	return new(fastReflection_PauserAddresses)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PauserAddresses) Interface() protoreflect.ProtoMessage {
	return (*PauserAddresses)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PauserAddresses) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Addresses) != 0 {
		value := protoreflect.ValueOfList(&_PauserAddresses_1_list{list: &x.Addresses})
		if !f(fd_PauserAddresses_addresses, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PauserAddresses) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.PauserAddresses.addresses":
		return len(x.Addresses) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.PauserAddresses"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.PauserAddresses does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PauserAddresses) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.PauserAddresses.addresses":
		x.Addresses = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.PauserAddresses"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.PauserAddresses does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PauserAddresses) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "zigchain.tokenwrapper.PauserAddresses.addresses":
		if len(x.Addresses) == 0 {
			return protoreflect.ValueOfList(&_PauserAddresses_1_list{})
		}
		listValue := &_PauserAddresses_1_list{list: &x.Addresses}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.PauserAddresses"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.PauserAddresses does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PauserAddresses) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.PauserAddresses.addresses":
		lv := value.List()
		clv := lv.(*_PauserAddresses_1_list)
		x.Addresses = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.PauserAddresses"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.PauserAddresses does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PauserAddresses) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.PauserAddresses.addresses":
		if x.Addresses == nil {
			x.Addresses = []string{}
		}
		value := &_PauserAddresses_1_list{list: &x.Addresses}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.PauserAddresses"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.PauserAddresses does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PauserAddresses) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.PauserAddresses.addresses":
		list := []string{}
		return protoreflect.ValueOfList(&_PauserAddresses_1_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.PauserAddresses"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.PauserAddresses does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PauserAddresses) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in zigchain.tokenwrapper.PauserAddresses", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PauserAddresses) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PauserAddresses) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PauserAddresses) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PauserAddresses) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PauserAddresses)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.Addresses) > 0 {
			for _, s := range x.Addresses {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PauserAddresses)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Addresses) > 0 {
			for iNdEx := len(x.Addresses) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Addresses[iNdEx])
				copy(dAtA[i:], x.Addresses[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Addresses[iNdEx])))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PauserAddresses)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PauserAddresses: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PauserAddresses: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Addresses = append(x.Addresses, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_GenesisState_6_list)(nil)

type _GenesisState_6_list struct {
	list *[]string
}

func (x *_GenesisState_6_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_6_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_GenesisState_6_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_6_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_6_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message GenesisState at list field PauserAddresses as it is not of Message kind"))
}

func (x *_GenesisState_6_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_6_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_GenesisState_6_list) IsValid() bool {
	return x.list != nil
}

var (
	md_GenesisState                           protoreflect.MessageDescriptor
	fd_GenesisState_params                    protoreflect.FieldDescriptor
	fd_GenesisState_total_transferred_in      protoreflect.FieldDescriptor
	fd_GenesisState_total_transferred_out     protoreflect.FieldDescriptor
	fd_GenesisState_operator_address          protoreflect.FieldDescriptor
	fd_GenesisState_proposed_operator_address protoreflect.FieldDescriptor
	fd_GenesisState_pauser_addresses          protoreflect.FieldDescriptor
	fd_GenesisState_enabled                   protoreflect.FieldDescriptor
	fd_GenesisState_native_client_id          protoreflect.FieldDescriptor
	fd_GenesisState_native_port               protoreflect.FieldDescriptor
	fd_GenesisState_native_channel            protoreflect.FieldDescriptor
	fd_GenesisState_denom                     protoreflect.FieldDescriptor
	fd_GenesisState_decimal_difference        protoreflect.FieldDescriptor
	fd_GenesisState_counterparty_client_id    protoreflect.FieldDescriptor
	fd_GenesisState_counterparty_port         protoreflect.FieldDescriptor
	fd_GenesisState_counterparty_channel      protoreflect.FieldDescriptor
)

func init() {
	file_zigchain_tokenwrapper_genesis_proto_init()
	md_GenesisState = File_zigchain_tokenwrapper_genesis_proto.Messages().ByName("GenesisState")
	fd_GenesisState_params = md_GenesisState.Fields().ByName("params")
	fd_GenesisState_total_transferred_in = md_GenesisState.Fields().ByName("total_transferred_in")
	fd_GenesisState_total_transferred_out = md_GenesisState.Fields().ByName("total_transferred_out")
	fd_GenesisState_operator_address = md_GenesisState.Fields().ByName("operator_address")
	fd_GenesisState_proposed_operator_address = md_GenesisState.Fields().ByName("proposed_operator_address")
	fd_GenesisState_pauser_addresses = md_GenesisState.Fields().ByName("pauser_addresses")
	fd_GenesisState_enabled = md_GenesisState.Fields().ByName("enabled")
	fd_GenesisState_native_client_id = md_GenesisState.Fields().ByName("native_client_id")
	fd_GenesisState_native_port = md_GenesisState.Fields().ByName("native_port")
	fd_GenesisState_native_channel = md_GenesisState.Fields().ByName("native_channel")
	fd_GenesisState_denom = md_GenesisState.Fields().ByName("denom")
	fd_GenesisState_decimal_difference = md_GenesisState.Fields().ByName("decimal_difference")
	fd_GenesisState_counterparty_client_id = md_GenesisState.Fields().ByName("counterparty_client_id")
	fd_GenesisState_counterparty_port = md_GenesisState.Fields().ByName("counterparty_port")
	fd_GenesisState_counterparty_channel = md_GenesisState.Fields().ByName("counterparty_channel")
}

var _ protoreflect.Message = (*fastReflection_GenesisState)(nil)

type fastReflection_GenesisState GenesisState

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	return (*fastReflection_GenesisState)(x)
}

func (x *GenesisState) slowProtoReflect() protoreflect.Message {
	mi := &file_zigchain_tokenwrapper_genesis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_GenesisState_messageType fastReflection_GenesisState_messageType
var _ protoreflect.MessageType = fastReflection_GenesisState_messageType{}

type fastReflection_GenesisState_messageType struct{}

func (x fastReflection_GenesisState_messageType) Zero() protoreflect.Message {
	return (*fastReflection_GenesisState)(nil)
}
func (x fastReflection_GenesisState_messageType) New() protoreflect.Message {
	return new(fastReflection_GenesisState)
}
func (x fastReflection_GenesisState_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_GenesisState
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_GenesisState) Descriptor() protoreflect.MessageDescriptor {
	return md_GenesisState
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_GenesisState) Type() protoreflect.MessageType {
	return _fastReflection_GenesisState_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_GenesisState) New() protoreflect.Message {
	return new(fastReflection_GenesisState)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_GenesisState) Interface() protoreflect.ProtoMessage {
	return (*GenesisState)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_GenesisState) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Params != nil {
		value := protoreflect.ValueOfMessage(x.Params.ProtoReflect())
		if !f(fd_GenesisState_params, value) {
			return
		}
	}
	if x.TotalTransferredIn != "" {
		value := protoreflect.ValueOfString(x.TotalTransferredIn)
		if !f(fd_GenesisState_total_transferred_in, value) {
			return
		}
	}
	if x.TotalTransferredOut != "" {
		value := protoreflect.ValueOfString(x.TotalTransferredOut)
		if !f(fd_GenesisState_total_transferred_out, value) {
			return
		}
	}
	if x.OperatorAddress != "" {
		value := protoreflect.ValueOfString(x.OperatorAddress)
		if !f(fd_GenesisState_operator_address, value) {
			return
		}
	}
	if x.ProposedOperatorAddress != "" {
		value := protoreflect.ValueOfString(x.ProposedOperatorAddress)
		if !f(fd_GenesisState_proposed_operator_address, value) {
			return
		}
	}
	if len(x.PauserAddresses) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_6_list{list: &x.PauserAddresses})
		if !f(fd_GenesisState_pauser_addresses, value) {
			return
		}
	}
	if x.Enabled != false {
		value := protoreflect.ValueOfBool(x.Enabled)
		if !f(fd_GenesisState_enabled, value) {
			return
		}
	}
	if x.NativeClientId != "" {
		value := protoreflect.ValueOfString(x.NativeClientId)
		if !f(fd_GenesisState_native_client_id, value) {
			return
		}
	}
	if x.NativePort != "" {
		value := protoreflect.ValueOfString(x.NativePort)
		if !f(fd_GenesisState_native_port, value) {
			return
		}
	}
	if x.NativeChannel != "" {
		value := protoreflect.ValueOfString(x.NativeChannel)
		if !f(fd_GenesisState_native_channel, value) {
			return
		}
	}
	if x.Denom != "" {
		value := protoreflect.ValueOfString(x.Denom)
		if !f(fd_GenesisState_denom, value) {
			return
		}
	}
	if x.DecimalDifference != uint32(0) {
		value := protoreflect.ValueOfUint32(x.DecimalDifference)
		if !f(fd_GenesisState_decimal_difference, value) {
			return
		}
	}
	if x.CounterpartyClientId != "" {
		value := protoreflect.ValueOfString(x.CounterpartyClientId)
		if !f(fd_GenesisState_counterparty_client_id, value) {
			return
		}
	}
	if x.CounterpartyPort != "" {
		value := protoreflect.ValueOfString(x.CounterpartyPort)
		if !f(fd_GenesisState_counterparty_port, value) {
			return
		}
	}
	if x.CounterpartyChannel != "" {
		value := protoreflect.ValueOfString(x.CounterpartyChannel)
		if !f(fd_GenesisState_counterparty_channel, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_GenesisState) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.GenesisState.params":
		return x.Params != nil
	case "zigchain.tokenwrapper.GenesisState.total_transferred_in":
		return x.TotalTransferredIn != ""
	case "zigchain.tokenwrapper.GenesisState.total_transferred_out":
		return x.TotalTransferredOut != ""
	case "zigchain.tokenwrapper.GenesisState.operator_address":
		return x.OperatorAddress != ""
	case "zigchain.tokenwrapper.GenesisState.proposed_operator_address":
		return x.ProposedOperatorAddress != ""
	case "zigchain.tokenwrapper.GenesisState.pauser_addresses":
		return len(x.PauserAddresses) != 0
	case "zigchain.tokenwrapper.GenesisState.enabled":
		return x.Enabled != false
	case "zigchain.tokenwrapper.GenesisState.native_client_id":
		return x.NativeClientId != ""
	case "zigchain.tokenwrapper.GenesisState.native_port":
		return x.NativePort != ""
	case "zigchain.tokenwrapper.GenesisState.native_channel":
		return x.NativeChannel != ""
	case "zigchain.tokenwrapper.GenesisState.denom":
		return x.Denom != ""
	case "zigchain.tokenwrapper.GenesisState.decimal_difference":
		return x.DecimalDifference != uint32(0)
	case "zigchain.tokenwrapper.GenesisState.counterparty_client_id":
		return x.CounterpartyClientId != ""
	case "zigchain.tokenwrapper.GenesisState.counterparty_port":
		return x.CounterpartyPort != ""
	case "zigchain.tokenwrapper.GenesisState.counterparty_channel":
		return x.CounterpartyChannel != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.GenesisState"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.GenesisState.params":
		x.Params = nil
	case "zigchain.tokenwrapper.GenesisState.total_transferred_in":
		x.TotalTransferredIn = ""
	case "zigchain.tokenwrapper.GenesisState.total_transferred_out":
		x.TotalTransferredOut = ""
	case "zigchain.tokenwrapper.GenesisState.operator_address":
		x.OperatorAddress = ""
	case "zigchain.tokenwrapper.GenesisState.proposed_operator_address":
		x.ProposedOperatorAddress = ""
	case "zigchain.tokenwrapper.GenesisState.pauser_addresses":
		x.PauserAddresses = nil
	case "zigchain.tokenwrapper.GenesisState.enabled":
		x.Enabled = false
	case "zigchain.tokenwrapper.GenesisState.native_client_id":
		x.NativeClientId = ""
	case "zigchain.tokenwrapper.GenesisState.native_port":
		x.NativePort = ""
	case "zigchain.tokenwrapper.GenesisState.native_channel":
		x.NativeChannel = ""
	case "zigchain.tokenwrapper.GenesisState.denom":
		x.Denom = ""
	case "zigchain.tokenwrapper.GenesisState.decimal_difference":
		x.DecimalDifference = uint32(0)
	case "zigchain.tokenwrapper.GenesisState.counterparty_client_id":
		x.CounterpartyClientId = ""
	case "zigchain.tokenwrapper.GenesisState.counterparty_port":
		x.CounterpartyPort = ""
	case "zigchain.tokenwrapper.GenesisState.counterparty_channel":
		x.CounterpartyChannel = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.GenesisState"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_GenesisState) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "zigchain.tokenwrapper.GenesisState.params":
		value := x.Params
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "zigchain.tokenwrapper.GenesisState.total_transferred_in":
		value := x.TotalTransferredIn
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.total_transferred_out":
		value := x.TotalTransferredOut
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.operator_address":
		value := x.OperatorAddress
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.proposed_operator_address":
		value := x.ProposedOperatorAddress
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.pauser_addresses":
		if len(x.PauserAddresses) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_6_list{})
		}
		listValue := &_GenesisState_6_list{list: &x.PauserAddresses}
		return protoreflect.ValueOfList(listValue)
	case "zigchain.tokenwrapper.GenesisState.enabled":
		value := x.Enabled
		return protoreflect.ValueOfBool(value)
	case "zigchain.tokenwrapper.GenesisState.native_client_id":
		value := x.NativeClientId
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.native_port":
		value := x.NativePort
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.native_channel":
		value := x.NativeChannel
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.denom":
		value := x.Denom
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.decimal_difference":
		value := x.DecimalDifference
		return protoreflect.ValueOfUint32(value)
	case "zigchain.tokenwrapper.GenesisState.counterparty_client_id":
		value := x.CounterpartyClientId
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.counterparty_port":
		value := x.CounterpartyPort
		return protoreflect.ValueOfString(value)
	case "zigchain.tokenwrapper.GenesisState.counterparty_channel":
		value := x.CounterpartyChannel
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.GenesisState"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.GenesisState does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.GenesisState.params":
		x.Params = value.Message().Interface().(*Params)
	case "zigchain.tokenwrapper.GenesisState.total_transferred_in":
		x.TotalTransferredIn = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.total_transferred_out":
		x.TotalTransferredOut = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.operator_address":
		x.OperatorAddress = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.proposed_operator_address":
		x.ProposedOperatorAddress = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.pauser_addresses":
		lv := value.List()
		clv := lv.(*_GenesisState_6_list)
		x.PauserAddresses = *clv.list
	case "zigchain.tokenwrapper.GenesisState.enabled":
		x.Enabled = value.Bool()
	case "zigchain.tokenwrapper.GenesisState.native_client_id":
		x.NativeClientId = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.native_port":
		x.NativePort = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.native_channel":
		x.NativeChannel = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.denom":
		x.Denom = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.decimal_difference":
		x.DecimalDifference = uint32(value.Uint())
	case "zigchain.tokenwrapper.GenesisState.counterparty_client_id":
		x.CounterpartyClientId = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.counterparty_port":
		x.CounterpartyPort = value.Interface().(string)
	case "zigchain.tokenwrapper.GenesisState.counterparty_channel":
		x.CounterpartyChannel = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.GenesisState"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.GenesisState.params":
		if x.Params == nil {
			x.Params = new(Params)
		}
		return protoreflect.ValueOfMessage(x.Params.ProtoReflect())
	case "zigchain.tokenwrapper.GenesisState.pauser_addresses":
		if x.PauserAddresses == nil {
			x.PauserAddresses = []string{}
		}
		value := &_GenesisState_6_list{list: &x.PauserAddresses}
		return protoreflect.ValueOfList(value)
	case "zigchain.tokenwrapper.GenesisState.total_transferred_in":
		panic(fmt.Errorf("field total_transferred_in of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.total_transferred_out":
		panic(fmt.Errorf("field total_transferred_out of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.operator_address":
		panic(fmt.Errorf("field operator_address of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.proposed_operator_address":
		panic(fmt.Errorf("field proposed_operator_address of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.enabled":
		panic(fmt.Errorf("field enabled of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.native_client_id":
		panic(fmt.Errorf("field native_client_id of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.native_port":
		panic(fmt.Errorf("field native_port of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.native_channel":
		panic(fmt.Errorf("field native_channel of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.denom":
		panic(fmt.Errorf("field denom of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.decimal_difference":
		panic(fmt.Errorf("field decimal_difference of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.counterparty_client_id":
		panic(fmt.Errorf("field counterparty_client_id of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.counterparty_port":
		panic(fmt.Errorf("field counterparty_port of message zigchain.tokenwrapper.GenesisState is not mutable"))
	case "zigchain.tokenwrapper.GenesisState.counterparty_channel":
		panic(fmt.Errorf("field counterparty_channel of message zigchain.tokenwrapper.GenesisState is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.GenesisState"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.GenesisState does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_GenesisState) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "zigchain.tokenwrapper.GenesisState.params":
		m := new(Params)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "zigchain.tokenwrapper.GenesisState.total_transferred_in":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.total_transferred_out":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.operator_address":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.proposed_operator_address":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.pauser_addresses":
		list := []string{}
		return protoreflect.ValueOfList(&_GenesisState_6_list{list: &list})
	case "zigchain.tokenwrapper.GenesisState.enabled":
		return protoreflect.ValueOfBool(false)
	case "zigchain.tokenwrapper.GenesisState.native_client_id":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.native_port":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.native_channel":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.denom":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.decimal_difference":
		return protoreflect.ValueOfUint32(uint32(0))
	case "zigchain.tokenwrapper.GenesisState.counterparty_client_id":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.counterparty_port":
		return protoreflect.ValueOfString("")
	case "zigchain.tokenwrapper.GenesisState.counterparty_channel":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: zigchain.tokenwrapper.GenesisState"))
		}
		panic(fmt.Errorf("message zigchain.tokenwrapper.GenesisState does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_GenesisState) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in zigchain.tokenwrapper.GenesisState", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_GenesisState) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_GenesisState) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_GenesisState) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Params != nil {
			l = options.Size(x.Params)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TotalTransferredIn)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TotalTransferredOut)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OperatorAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ProposedOperatorAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.PauserAddresses) > 0 {
			for _, s := range x.PauserAddresses {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.Enabled {
			n += 2
		}
		l = len(x.NativeClientId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NativePort)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NativeChannel)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Denom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.DecimalDifference != 0 {
			n += 1 + runtime.Sov(uint64(x.DecimalDifference))
		}
		l = len(x.CounterpartyClientId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.CounterpartyPort)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.CounterpartyChannel)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.CounterpartyChannel) > 0 {
			i -= len(x.CounterpartyChannel)
			copy(dAtA[i:], x.CounterpartyChannel)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CounterpartyChannel)))
			i--
			dAtA[i] = 0x7a
		}
		if len(x.CounterpartyPort) > 0 {
			i -= len(x.CounterpartyPort)
			copy(dAtA[i:], x.CounterpartyPort)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CounterpartyPort)))
			i--
			dAtA[i] = 0x72
		}
		if len(x.CounterpartyClientId) > 0 {
			i -= len(x.CounterpartyClientId)
			copy(dAtA[i:], x.CounterpartyClientId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CounterpartyClientId)))
			i--
			dAtA[i] = 0x6a
		}
		if x.DecimalDifference != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DecimalDifference))
			i--
			dAtA[i] = 0x60
		}
		if len(x.Denom) > 0 {
			i -= len(x.Denom)
			copy(dAtA[i:], x.Denom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Denom)))
			i--
			dAtA[i] = 0x5a
		}
		if len(x.NativeChannel) > 0 {
			i -= len(x.NativeChannel)
			copy(dAtA[i:], x.NativeChannel)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NativeChannel)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.NativePort) > 0 {
			i -= len(x.NativePort)
			copy(dAtA[i:], x.NativePort)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NativePort)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.NativeClientId) > 0 {
			i -= len(x.NativeClientId)
			copy(dAtA[i:], x.NativeClientId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NativeClientId)))
			i--
			dAtA[i] = 0x42
		}
		if x.Enabled {
			i--
			if x.Enabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x38
		}
		if len(x.PauserAddresses) > 0 {
			for iNdEx := len(x.PauserAddresses) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.PauserAddresses[iNdEx])
				copy(dAtA[i:], x.PauserAddresses[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PauserAddresses[iNdEx])))
				i--
				dAtA[i] = 0x32
			}
		}
		if len(x.ProposedOperatorAddress) > 0 {
			i -= len(x.ProposedOperatorAddress)
			copy(dAtA[i:], x.ProposedOperatorAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ProposedOperatorAddress)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.OperatorAddress) > 0 {
			i -= len(x.OperatorAddress)
			copy(dAtA[i:], x.OperatorAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OperatorAddress)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.TotalTransferredOut) > 0 {
			i -= len(x.TotalTransferredOut)
			copy(dAtA[i:], x.TotalTransferredOut)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalTransferredOut)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.TotalTransferredIn) > 0 {
			i -= len(x.TotalTransferredIn)
			copy(dAtA[i:], x.TotalTransferredIn)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalTransferredIn)))
			i--
			dAtA[i] = 0x12
		}
		if x.Params != nil {
			encoded, err := options.Marshal(x.Params)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Params == nil {
					x.Params = &Params{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Params); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalTransferredIn", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalTransferredIn = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalTransferredOut", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalTransferredOut = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OperatorAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProposedOperatorAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ProposedOperatorAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PauserAddresses", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PauserAddresses = append(x.PauserAddresses, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Enabled = bool(v != 0)
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NativeClientId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NativeClientId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NativePort", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NativePort = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NativeChannel", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NativeChannel = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Denom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DecimalDifference", wireType)
				}
				x.DecimalDifference = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DecimalDifference |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 13:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CounterpartyClientId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CounterpartyClientId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 14:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CounterpartyPort", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CounterpartyPort = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 15:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CounterpartyChannel", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CounterpartyChannel = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: zigchain/tokenwrapper/genesis.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PauserAddresses represents a list of pauser addresses
type PauserAddresses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *PauserAddresses) Reset() {
	*x = PauserAddresses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigchain_tokenwrapper_genesis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauserAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauserAddresses) ProtoMessage() {}

// Deprecated: Use PauserAddresses.ProtoReflect.Descriptor instead.
func (*PauserAddresses) Descriptor() ([]byte, []int) {
	return file_zigchain_tokenwrapper_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *PauserAddresses) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// GenesisState defines the tokenwrapper module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// params defines all the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// total_transferred_in defines the total amount of ZIG tokens transferred in
	TotalTransferredIn string `protobuf:"bytes,2,opt,name=total_transferred_in,json=totalTransferredIn,proto3" json:"total_transferred_in,omitempty"`
	// total_transferred_out defines the total amount of ZIG tokens transferred
	// out
	TotalTransferredOut string `protobuf:"bytes,3,opt,name=total_transferred_out,json=totalTransferredOut,proto3" json:"total_transferred_out,omitempty"`
	// operator_address defines the address that has permission to update operator
	// and control module state
	OperatorAddress string `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	// proposed_operator_address defines the address that has proposed to update
	// operator and control module state
	ProposedOperatorAddress string `protobuf:"bytes,5,opt,name=proposed_operator_address,json=proposedOperatorAddress,proto3" json:"proposed_operator_address,omitempty"`
	// pauser_addresses defines the list of addresses that have permission to
	// pause or disable the token wrapper module
	PauserAddresses []string `protobuf:"bytes,6,rep,name=pauser_addresses,json=pauserAddresses,proto3" json:"pauser_addresses,omitempty"`
	// enabled defines whether the token wrapper functionality is enabled
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// native_client_id defines the client ID of the source chain
	NativeClientId string `protobuf:"bytes,8,opt,name=native_client_id,json=nativeClientId,proto3" json:"native_client_id,omitempty"`
	// native_port defines the port ID of the source chain
	NativePort string `protobuf:"bytes,9,opt,name=native_port,json=nativePort,proto3" json:"native_port,omitempty"`
	// native_channel defines the channel ID of the source chain
	NativeChannel string `protobuf:"bytes,10,opt,name=native_channel,json=nativeChannel,proto3" json:"native_channel,omitempty"`
	// denom defines the denomination of the token
	Denom string `protobuf:"bytes,11,opt,name=denom,proto3" json:"denom,omitempty"`
	// decimal difference between Axelar ZIG (18 decimals) and ZIGChain native ZIG
	// (6 decimals)
	DecimalDifference uint32 `protobuf:"varint,12,opt,name=decimal_difference,json=decimalDifference,proto3" json:"decimal_difference,omitempty"`
	// counterparty_client_id defines the client ID of the destination chain
	CounterpartyClientId string `protobuf:"bytes,13,opt,name=counterparty_client_id,json=counterpartyClientId,proto3" json:"counterparty_client_id,omitempty"`
	// counterparty_port defines the port ID of the destination chain
	CounterpartyPort string `protobuf:"bytes,14,opt,name=counterparty_port,json=counterpartyPort,proto3" json:"counterparty_port,omitempty"`
	// counterparty_channel defines the channel ID of the destination chain
	CounterpartyChannel string `protobuf:"bytes,15,opt,name=counterparty_channel,json=counterpartyChannel,proto3" json:"counterparty_channel,omitempty"`
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigchain_tokenwrapper_genesis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_zigchain_tokenwrapper_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetTotalTransferredIn() string {
	if x != nil {
		return x.TotalTransferredIn
	}
	return ""
}

func (x *GenesisState) GetTotalTransferredOut() string {
	if x != nil {
		return x.TotalTransferredOut
	}
	return ""
}

func (x *GenesisState) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

func (x *GenesisState) GetProposedOperatorAddress() string {
	if x != nil {
		return x.ProposedOperatorAddress
	}
	return ""
}

func (x *GenesisState) GetPauserAddresses() []string {
	if x != nil {
		return x.PauserAddresses
	}
	return nil
}

func (x *GenesisState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GenesisState) GetNativeClientId() string {
	if x != nil {
		return x.NativeClientId
	}
	return ""
}

func (x *GenesisState) GetNativePort() string {
	if x != nil {
		return x.NativePort
	}
	return ""
}

func (x *GenesisState) GetNativeChannel() string {
	if x != nil {
		return x.NativeChannel
	}
	return ""
}

func (x *GenesisState) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *GenesisState) GetDecimalDifference() uint32 {
	if x != nil {
		return x.DecimalDifference
	}
	return 0
}

func (x *GenesisState) GetCounterpartyClientId() string {
	if x != nil {
		return x.CounterpartyClientId
	}
	return ""
}

func (x *GenesisState) GetCounterpartyPort() string {
	if x != nil {
		return x.CounterpartyPort
	}
	return ""
}

func (x *GenesisState) GetCounterpartyChannel() string {
	if x != nil {
		return x.CounterpartyChannel
	}
	return ""
}

var File_zigchain_tokenwrapper_genesis_proto protoreflect.FileDescriptor

var file_zigchain_tokenwrapper_genesis_proto_rawDesc = []byte{
	0x0a, 0x23, 0x7a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x7a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x1a, 0x11, 0x61, 0x6d,
	0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x22, 0x7a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x50, 0x61, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22,
	0xbb, 0x06, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x40, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x7a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42,
	0x09, 0xc8, 0xde, 0x1f, 0x00, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x4f, 0x0a, 0x14, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x1d, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74, 0x52,
	0x12, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65,
	0x64, 0x49, 0x6e, 0x12, 0x51, 0x0a, 0x15, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x1d, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e,
	0x74, 0x52, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x54, 0x0a, 0x19, 0x70,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18,
	0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x17, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x43, 0x0a, 0x10, 0x70, 0x61, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d,
	0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x10, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61,
	0x74, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6e,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x65, 0x63, 0x69,
	0x6d, 0x61, 0x6c, 0x5f, 0x64, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x44, 0x69, 0x66,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a,
	0x11, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0xc6, 0x01,
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x7a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x42, 0x0c, 0x47, 0x65, 0x6e,
	0x65, 0x73, 0x69, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x7a, 0x69,
	0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x77, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x5a, 0x54, 0x58, 0xaa, 0x02, 0x15, 0x5a, 0x69, 0x67, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0xca, 0x02, 0x15, 0x5a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0xe2, 0x02, 0x21, 0x5a, 0x69, 0x67, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16,
	0x5a, 0x69, 0x67, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zigchain_tokenwrapper_genesis_proto_rawDescOnce sync.Once
	file_zigchain_tokenwrapper_genesis_proto_rawDescData = file_zigchain_tokenwrapper_genesis_proto_rawDesc
)

func file_zigchain_tokenwrapper_genesis_proto_rawDescGZIP() []byte {
	file_zigchain_tokenwrapper_genesis_proto_rawDescOnce.Do(func() {
		file_zigchain_tokenwrapper_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(file_zigchain_tokenwrapper_genesis_proto_rawDescData)
	})
	return file_zigchain_tokenwrapper_genesis_proto_rawDescData
}

var file_zigchain_tokenwrapper_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zigchain_tokenwrapper_genesis_proto_goTypes = []interface{}{
	(*PauserAddresses)(nil), // 0: zigchain.tokenwrapper.PauserAddresses
	(*GenesisState)(nil),    // 1: zigchain.tokenwrapper.GenesisState
	(*Params)(nil),          // 2: zigchain.tokenwrapper.Params
}
var file_zigchain_tokenwrapper_genesis_proto_depIdxs = []int32{
	2, // 0: zigchain.tokenwrapper.GenesisState.params:type_name -> zigchain.tokenwrapper.Params
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zigchain_tokenwrapper_genesis_proto_init() }
func file_zigchain_tokenwrapper_genesis_proto_init() {
	if File_zigchain_tokenwrapper_genesis_proto != nil {
		return
	}
	file_zigchain_tokenwrapper_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_zigchain_tokenwrapper_genesis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauserAddresses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigchain_tokenwrapper_genesis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenesisState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zigchain_tokenwrapper_genesis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zigchain_tokenwrapper_genesis_proto_goTypes,
		DependencyIndexes: file_zigchain_tokenwrapper_genesis_proto_depIdxs,
		MessageInfos:      file_zigchain_tokenwrapper_genesis_proto_msgTypes,
	}.Build()
	File_zigchain_tokenwrapper_genesis_proto = out.File
	file_zigchain_tokenwrapper_genesis_proto_rawDesc = nil
	file_zigchain_tokenwrapper_genesis_proto_goTypes = nil
	file_zigchain_tokenwrapper_genesis_proto_depIdxs = nil
}
