// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: zigchain/tokenwrapper/tx.proto

package tokenwrapper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_UpdateParams_FullMethodName             = "/zigchain.tokenwrapper.Msg/UpdateParams"
	Msg_FundModuleWallet_FullMethodName         = "/zigchain.tokenwrapper.Msg/FundModuleWallet"
	Msg_WithdrawFromModuleWallet_FullMethodName = "/zigchain.tokenwrapper.Msg/WithdrawFromModuleWallet"
	Msg_EnableTokenWrapper_FullMethodName       = "/zigchain.tokenwrapper.Msg/EnableTokenWrapper"
	Msg_DisableTokenWrapper_FullMethodName      = "/zigchain.tokenwrapper.Msg/DisableTokenWrapper"
	Msg_UpdateIbcSettings_FullMethodName        = "/zigchain.tokenwrapper.Msg/UpdateIbcSettings"
	Msg_AddPauserAddress_FullMethodName         = "/zigchain.tokenwrapper.Msg/AddPauserAddress"
	Msg_RemovePauserAddress_FullMethodName      = "/zigchain.tokenwrapper.Msg/RemovePauserAddress"
	Msg_ProposeOperatorAddress_FullMethodName   = "/zigchain.tokenwrapper.Msg/ProposeOperatorAddress"
	Msg_ClaimOperatorAddress_FullMethodName     = "/zigchain.tokenwrapper.Msg/ClaimOperatorAddress"
	Msg_RecoverZig_FullMethodName               = "/zigchain.tokenwrapper.Msg/RecoverZig"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	FundModuleWallet(ctx context.Context, in *MsgFundModuleWallet, opts ...grpc.CallOption) (*MsgFundModuleWalletResponse, error)
	WithdrawFromModuleWallet(ctx context.Context, in *MsgWithdrawFromModuleWallet, opts ...grpc.CallOption) (*MsgWithdrawFromModuleWalletResponse, error)
	EnableTokenWrapper(ctx context.Context, in *MsgEnableTokenWrapper, opts ...grpc.CallOption) (*MsgEnableTokenWrapperResponse, error)
	DisableTokenWrapper(ctx context.Context, in *MsgDisableTokenWrapper, opts ...grpc.CallOption) (*MsgDisableTokenWrapperResponse, error)
	UpdateIbcSettings(ctx context.Context, in *MsgUpdateIbcSettings, opts ...grpc.CallOption) (*MsgUpdateIbcSettingsResponse, error)
	AddPauserAddress(ctx context.Context, in *MsgAddPauserAddress, opts ...grpc.CallOption) (*MsgAddPauserAddressResponse, error)
	RemovePauserAddress(ctx context.Context, in *MsgRemovePauserAddress, opts ...grpc.CallOption) (*MsgRemovePauserAddressResponse, error)
	ProposeOperatorAddress(ctx context.Context, in *MsgProposeOperatorAddress, opts ...grpc.CallOption) (*MsgProposeOperatorAddressResponse, error)
	ClaimOperatorAddress(ctx context.Context, in *MsgClaimOperatorAddress, opts ...grpc.CallOption) (*MsgClaimOperatorAddressResponse, error)
	RecoverZig(ctx context.Context, in *MsgRecoverZig, opts ...grpc.CallOption) (*MsgRecoverZigResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FundModuleWallet(ctx context.Context, in *MsgFundModuleWallet, opts ...grpc.CallOption) (*MsgFundModuleWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgFundModuleWalletResponse)
	err := c.cc.Invoke(ctx, Msg_FundModuleWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawFromModuleWallet(ctx context.Context, in *MsgWithdrawFromModuleWallet, opts ...grpc.CallOption) (*MsgWithdrawFromModuleWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgWithdrawFromModuleWalletResponse)
	err := c.cc.Invoke(ctx, Msg_WithdrawFromModuleWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EnableTokenWrapper(ctx context.Context, in *MsgEnableTokenWrapper, opts ...grpc.CallOption) (*MsgEnableTokenWrapperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgEnableTokenWrapperResponse)
	err := c.cc.Invoke(ctx, Msg_EnableTokenWrapper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableTokenWrapper(ctx context.Context, in *MsgDisableTokenWrapper, opts ...grpc.CallOption) (*MsgDisableTokenWrapperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDisableTokenWrapperResponse)
	err := c.cc.Invoke(ctx, Msg_DisableTokenWrapper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateIbcSettings(ctx context.Context, in *MsgUpdateIbcSettings, opts ...grpc.CallOption) (*MsgUpdateIbcSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateIbcSettingsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateIbcSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddPauserAddress(ctx context.Context, in *MsgAddPauserAddress, opts ...grpc.CallOption) (*MsgAddPauserAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAddPauserAddressResponse)
	err := c.cc.Invoke(ctx, Msg_AddPauserAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemovePauserAddress(ctx context.Context, in *MsgRemovePauserAddress, opts ...grpc.CallOption) (*MsgRemovePauserAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRemovePauserAddressResponse)
	err := c.cc.Invoke(ctx, Msg_RemovePauserAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProposeOperatorAddress(ctx context.Context, in *MsgProposeOperatorAddress, opts ...grpc.CallOption) (*MsgProposeOperatorAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgProposeOperatorAddressResponse)
	err := c.cc.Invoke(ctx, Msg_ProposeOperatorAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimOperatorAddress(ctx context.Context, in *MsgClaimOperatorAddress, opts ...grpc.CallOption) (*MsgClaimOperatorAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgClaimOperatorAddressResponse)
	err := c.cc.Invoke(ctx, Msg_ClaimOperatorAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RecoverZig(ctx context.Context, in *MsgRecoverZig, opts ...grpc.CallOption) (*MsgRecoverZigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRecoverZigResponse)
	err := c.cc.Invoke(ctx, Msg_RecoverZig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	FundModuleWallet(context.Context, *MsgFundModuleWallet) (*MsgFundModuleWalletResponse, error)
	WithdrawFromModuleWallet(context.Context, *MsgWithdrawFromModuleWallet) (*MsgWithdrawFromModuleWalletResponse, error)
	EnableTokenWrapper(context.Context, *MsgEnableTokenWrapper) (*MsgEnableTokenWrapperResponse, error)
	DisableTokenWrapper(context.Context, *MsgDisableTokenWrapper) (*MsgDisableTokenWrapperResponse, error)
	UpdateIbcSettings(context.Context, *MsgUpdateIbcSettings) (*MsgUpdateIbcSettingsResponse, error)
	AddPauserAddress(context.Context, *MsgAddPauserAddress) (*MsgAddPauserAddressResponse, error)
	RemovePauserAddress(context.Context, *MsgRemovePauserAddress) (*MsgRemovePauserAddressResponse, error)
	ProposeOperatorAddress(context.Context, *MsgProposeOperatorAddress) (*MsgProposeOperatorAddressResponse, error)
	ClaimOperatorAddress(context.Context, *MsgClaimOperatorAddress) (*MsgClaimOperatorAddressResponse, error)
	RecoverZig(context.Context, *MsgRecoverZig) (*MsgRecoverZigResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) FundModuleWallet(context.Context, *MsgFundModuleWallet) (*MsgFundModuleWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundModuleWallet not implemented")
}
func (UnimplementedMsgServer) WithdrawFromModuleWallet(context.Context, *MsgWithdrawFromModuleWallet) (*MsgWithdrawFromModuleWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawFromModuleWallet not implemented")
}
func (UnimplementedMsgServer) EnableTokenWrapper(context.Context, *MsgEnableTokenWrapper) (*MsgEnableTokenWrapperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableTokenWrapper not implemented")
}
func (UnimplementedMsgServer) DisableTokenWrapper(context.Context, *MsgDisableTokenWrapper) (*MsgDisableTokenWrapperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableTokenWrapper not implemented")
}
func (UnimplementedMsgServer) UpdateIbcSettings(context.Context, *MsgUpdateIbcSettings) (*MsgUpdateIbcSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIbcSettings not implemented")
}
func (UnimplementedMsgServer) AddPauserAddress(context.Context, *MsgAddPauserAddress) (*MsgAddPauserAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPauserAddress not implemented")
}
func (UnimplementedMsgServer) RemovePauserAddress(context.Context, *MsgRemovePauserAddress) (*MsgRemovePauserAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePauserAddress not implemented")
}
func (UnimplementedMsgServer) ProposeOperatorAddress(context.Context, *MsgProposeOperatorAddress) (*MsgProposeOperatorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeOperatorAddress not implemented")
}
func (UnimplementedMsgServer) ClaimOperatorAddress(context.Context, *MsgClaimOperatorAddress) (*MsgClaimOperatorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimOperatorAddress not implemented")
}
func (UnimplementedMsgServer) RecoverZig(context.Context, *MsgRecoverZig) (*MsgRecoverZigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverZig not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FundModuleWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFundModuleWallet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FundModuleWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FundModuleWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FundModuleWallet(ctx, req.(*MsgFundModuleWallet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawFromModuleWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawFromModuleWallet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawFromModuleWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_WithdrawFromModuleWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawFromModuleWallet(ctx, req.(*MsgWithdrawFromModuleWallet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EnableTokenWrapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnableTokenWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EnableTokenWrapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_EnableTokenWrapper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EnableTokenWrapper(ctx, req.(*MsgEnableTokenWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableTokenWrapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableTokenWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableTokenWrapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DisableTokenWrapper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableTokenWrapper(ctx, req.(*MsgDisableTokenWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateIbcSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateIbcSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateIbcSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateIbcSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateIbcSettings(ctx, req.(*MsgUpdateIbcSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddPauserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddPauserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddPauserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddPauserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddPauserAddress(ctx, req.(*MsgAddPauserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemovePauserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemovePauserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemovePauserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemovePauserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemovePauserAddress(ctx, req.(*MsgRemovePauserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProposeOperatorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeOperatorAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeOperatorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ProposeOperatorAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeOperatorAddress(ctx, req.(*MsgProposeOperatorAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimOperatorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimOperatorAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimOperatorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClaimOperatorAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimOperatorAddress(ctx, req.(*MsgClaimOperatorAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RecoverZig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecoverZig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecoverZig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RecoverZig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecoverZig(ctx, req.(*MsgRecoverZig))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zigchain.tokenwrapper.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "FundModuleWallet",
			Handler:    _Msg_FundModuleWallet_Handler,
		},
		{
			MethodName: "WithdrawFromModuleWallet",
			Handler:    _Msg_WithdrawFromModuleWallet_Handler,
		},
		{
			MethodName: "EnableTokenWrapper",
			Handler:    _Msg_EnableTokenWrapper_Handler,
		},
		{
			MethodName: "DisableTokenWrapper",
			Handler:    _Msg_DisableTokenWrapper_Handler,
		},
		{
			MethodName: "UpdateIbcSettings",
			Handler:    _Msg_UpdateIbcSettings_Handler,
		},
		{
			MethodName: "AddPauserAddress",
			Handler:    _Msg_AddPauserAddress_Handler,
		},
		{
			MethodName: "RemovePauserAddress",
			Handler:    _Msg_RemovePauserAddress_Handler,
		},
		{
			MethodName: "ProposeOperatorAddress",
			Handler:    _Msg_ProposeOperatorAddress_Handler,
		},
		{
			MethodName: "ClaimOperatorAddress",
			Handler:    _Msg_ClaimOperatorAddress_Handler,
		},
		{
			MethodName: "RecoverZig",
			Handler:    _Msg_RecoverZig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zigchain/tokenwrapper/tx.proto",
}
