// Code generated by MockGen. DO NOT EDIT.
// Source: x/factory/module/module.go
//
// Generated by this command:
//
//	mockgen -source=x/factory/module/module.go -package mock -destination x/factory/testutil/mock/types_module_module.go
//

// Package mock is a generated GoMock package.
package mock
