// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: zigchain/factory/query.proto

package factory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName        = "/zigchain.factory.Query/Params"
	Query_Denom_FullMethodName         = "/zigchain.factory.Query/Denom"
	Query_DenomAll_FullMethodName      = "/zigchain.factory.Query/DenomAll"
	Query_DenomsByAdmin_FullMethodName = "/zigchain.factory.Query/DenomsByAdmin"
	Query_DenomAuth_FullMethodName     = "/zigchain.factory.Query/DenomAuth"
	Query_ListDenomAuth_FullMethodName = "/zigchain.factory.Query/ListDenomAuth"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service.
type QueryClient interface {
	// QueryParams Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// QueryDenom Queries a list of Denom items.
	Denom(ctx context.Context, in *QueryGetDenomRequest, opts ...grpc.CallOption) (*QueryDenomResponse, error)
	// Queries a list of Denom items.
	DenomAll(ctx context.Context, in *QueryAllDenomRequest, opts ...grpc.CallOption) (*QueryAllDenomResponse, error)
	// QueryDenomsByAdmin Queries a list of Denom items.
	DenomsByAdmin(ctx context.Context, in *QueryDenomByAdminRequest, opts ...grpc.CallOption) (*QueryDenomByAdminResponse, error)
	// QueryGetDenomAuth a denom DenomAuth items.
	DenomAuth(ctx context.Context, in *QueryGetDenomAuthRequest, opts ...grpc.CallOption) (*QueryDenomAuthResponse, error)
	// QueryListDenomAuth queries a list of DenomAuth items.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ListDenomAuth(ctx context.Context, in *QueryAllDenomAuthRequest, opts ...grpc.CallOption) (*QueryAllDenomAuthResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Denom(ctx context.Context, in *QueryGetDenomRequest, opts ...grpc.CallOption) (*QueryDenomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDenomResponse)
	err := c.cc.Invoke(ctx, Query_Denom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomAll(ctx context.Context, in *QueryAllDenomRequest, opts ...grpc.CallOption) (*QueryAllDenomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAllDenomResponse)
	err := c.cc.Invoke(ctx, Query_DenomAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomsByAdmin(ctx context.Context, in *QueryDenomByAdminRequest, opts ...grpc.CallOption) (*QueryDenomByAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDenomByAdminResponse)
	err := c.cc.Invoke(ctx, Query_DenomsByAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomAuth(ctx context.Context, in *QueryGetDenomAuthRequest, opts ...grpc.CallOption) (*QueryDenomAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDenomAuthResponse)
	err := c.cc.Invoke(ctx, Query_DenomAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDenomAuth(ctx context.Context, in *QueryAllDenomAuthRequest, opts ...grpc.CallOption) (*QueryAllDenomAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAllDenomAuthResponse)
	err := c.cc.Invoke(ctx, Query_ListDenomAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service.
type QueryServer interface {
	// QueryParams Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// QueryDenom Queries a list of Denom items.
	Denom(context.Context, *QueryGetDenomRequest) (*QueryDenomResponse, error)
	// Queries a list of Denom items.
	DenomAll(context.Context, *QueryAllDenomRequest) (*QueryAllDenomResponse, error)
	// QueryDenomsByAdmin Queries a list of Denom items.
	DenomsByAdmin(context.Context, *QueryDenomByAdminRequest) (*QueryDenomByAdminResponse, error)
	// QueryGetDenomAuth a denom DenomAuth items.
	DenomAuth(context.Context, *QueryGetDenomAuthRequest) (*QueryDenomAuthResponse, error)
	// QueryListDenomAuth queries a list of DenomAuth items.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ListDenomAuth(context.Context, *QueryAllDenomAuthRequest) (*QueryAllDenomAuthResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Denom(context.Context, *QueryGetDenomRequest) (*QueryDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Denom not implemented")
}
func (UnimplementedQueryServer) DenomAll(context.Context, *QueryAllDenomRequest) (*QueryAllDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomAll not implemented")
}
func (UnimplementedQueryServer) DenomsByAdmin(context.Context, *QueryDenomByAdminRequest) (*QueryDenomByAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomsByAdmin not implemented")
}
func (UnimplementedQueryServer) DenomAuth(context.Context, *QueryGetDenomAuthRequest) (*QueryDenomAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomAuth not implemented")
}
func (UnimplementedQueryServer) ListDenomAuth(context.Context, *QueryAllDenomAuthRequest) (*QueryAllDenomAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDenomAuth not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Denom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDenomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Denom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Denom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Denom(ctx, req.(*QueryGetDenomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDenomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DenomAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomAll(ctx, req.(*QueryAllDenomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomsByAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDenomByAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomsByAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DenomsByAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomsByAdmin(ctx, req.(*QueryDenomByAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDenomAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DenomAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomAuth(ctx, req.(*QueryGetDenomAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDenomAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDenomAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDenomAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListDenomAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDenomAuth(ctx, req.(*QueryAllDenomAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zigchain.factory.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Denom",
			Handler:    _Query_Denom_Handler,
		},
		{
			MethodName: "DenomAll",
			Handler:    _Query_DenomAll_Handler,
		},
		{
			MethodName: "DenomsByAdmin",
			Handler:    _Query_DenomsByAdmin_Handler,
		},
		{
			MethodName: "DenomAuth",
			Handler:    _Query_DenomAuth_Handler,
		},
		{
			MethodName: "ListDenomAuth",
			Handler:    _Query_ListDenomAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zigchain/factory/query.proto",
}
