// this file defines the Msg service (transactions)  for the factory module

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: zigchain/factory/tx.proto

package factory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_UpdateParams_FullMethodName            = "/zigchain.factory.Msg/UpdateParams"
	Msg_CreateDenom_FullMethodName             = "/zigchain.factory.Msg/CreateDenom"
	Msg_SetDenomMetadata_FullMethodName        = "/zigchain.factory.Msg/SetDenomMetadata"
	Msg_UpdateDenomURI_FullMethodName          = "/zigchain.factory.Msg/UpdateDenomURI"
	Msg_UpdateDenomMintingCap_FullMethodName   = "/zigchain.factory.Msg/UpdateDenomMintingCap"
	Msg_UpdateDenomMetadataAuth_FullMethodName = "/zigchain.factory.Msg/UpdateDenomMetadataAuth"
	Msg_MintAndSendTokens_FullMethodName       = "/zigchain.factory.Msg/MintAndSendTokens"
	Msg_BurnTokens_FullMethodName              = "/zigchain.factory.Msg/BurnTokens"
	Msg_WithdrawModuleFees_FullMethodName      = "/zigchain.factory.Msg/WithdrawModuleFees"
	Msg_ProposeDenomAdmin_FullMethodName       = "/zigchain.factory.Msg/ProposeDenomAdmin"
	Msg_ClaimDenomAdmin_FullMethodName         = "/zigchain.factory.Msg/ClaimDenomAdmin"
	Msg_DisableDenomAdmin_FullMethodName       = "/zigchain.factory.Msg/DisableDenomAdmin"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// Create token
	CreateDenom(ctx context.Context, in *MsgCreateDenom, opts ...grpc.CallOption) (*MsgCreateDenomResponse, error)
	// Set the metadata of a denom
	SetDenomMetadata(ctx context.Context, in *MsgSetDenomMetadata, opts ...grpc.CallOption) (*MsgSetDenomMetadataResponse, error)
	// UpdateDenomURI updates the URI of a denom and its sha256 hash, only bank
	// admin can do it.
	UpdateDenomURI(ctx context.Context, in *MsgUpdateDenomURI, opts ...grpc.CallOption) (*MsgUpdateDenomURIResponse, error)
	// UpdateDenomMintingCap updates the minting cap and options o lock minting
	// cap changes on a denom, only bank admin can do it.
	UpdateDenomMintingCap(ctx context.Context, in *MsgUpdateDenomMintingCap, opts ...grpc.CallOption) (*MsgUpdateDenomMintingCapResponse, error)
	// UpdateDenomMetadataAuth updates the metadata admin of a denom, needed for
	// case when bank admin is disabled
	UpdateDenomMetadataAuth(ctx context.Context, in *MsgUpdateDenomMetadataAuth, opts ...grpc.CallOption) (*MsgUpdateDenomMetadataAuthResponse, error)
	// Mint and send tokens to a recipient
	MintAndSendTokens(ctx context.Context, in *MsgMintAndSendTokens, opts ...grpc.CallOption) (*MsgMintAndSendTokensResponse, error)
	// BurnTokens - Burn tokens from the signer's account, signer has to be bank
	// admin to do it.
	BurnTokens(ctx context.Context, in *MsgBurnTokens, opts ...grpc.CallOption) (*MsgBurnTokensResponse, error)
	WithdrawModuleFees(ctx context.Context, in *MsgWithdrawModuleFees, opts ...grpc.CallOption) (*MsgWithdrawModuleFeesResponse, error)
	// ProposeDenomAdmin represents a message to propose a new denom admin
	ProposeDenomAdmin(ctx context.Context, in *MsgProposeDenomAdmin, opts ...grpc.CallOption) (*MsgProposeDenomAdminResponse, error)
	// ClaimDenomAdmin represents a message to claim the denom admin role
	ClaimDenomAdmin(ctx context.Context, in *MsgClaimDenomAdmin, opts ...grpc.CallOption) (*MsgClaimDenomAdminResponse, error)
	// DisableDenomAdmin represents a message to disable the denom admin role
	DisableDenomAdmin(ctx context.Context, in *MsgDisableDenomAdmin, opts ...grpc.CallOption) (*MsgDisableDenomAdminResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateDenom(ctx context.Context, in *MsgCreateDenom, opts ...grpc.CallOption) (*MsgCreateDenomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateDenomResponse)
	err := c.cc.Invoke(ctx, Msg_CreateDenom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetDenomMetadata(ctx context.Context, in *MsgSetDenomMetadata, opts ...grpc.CallOption) (*MsgSetDenomMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSetDenomMetadataResponse)
	err := c.cc.Invoke(ctx, Msg_SetDenomMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDenomURI(ctx context.Context, in *MsgUpdateDenomURI, opts ...grpc.CallOption) (*MsgUpdateDenomURIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateDenomURIResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateDenomURI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDenomMintingCap(ctx context.Context, in *MsgUpdateDenomMintingCap, opts ...grpc.CallOption) (*MsgUpdateDenomMintingCapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateDenomMintingCapResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateDenomMintingCap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDenomMetadataAuth(ctx context.Context, in *MsgUpdateDenomMetadataAuth, opts ...grpc.CallOption) (*MsgUpdateDenomMetadataAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateDenomMetadataAuthResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateDenomMetadataAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintAndSendTokens(ctx context.Context, in *MsgMintAndSendTokens, opts ...grpc.CallOption) (*MsgMintAndSendTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgMintAndSendTokensResponse)
	err := c.cc.Invoke(ctx, Msg_MintAndSendTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnTokens(ctx context.Context, in *MsgBurnTokens, opts ...grpc.CallOption) (*MsgBurnTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgBurnTokensResponse)
	err := c.cc.Invoke(ctx, Msg_BurnTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawModuleFees(ctx context.Context, in *MsgWithdrawModuleFees, opts ...grpc.CallOption) (*MsgWithdrawModuleFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgWithdrawModuleFeesResponse)
	err := c.cc.Invoke(ctx, Msg_WithdrawModuleFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProposeDenomAdmin(ctx context.Context, in *MsgProposeDenomAdmin, opts ...grpc.CallOption) (*MsgProposeDenomAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgProposeDenomAdminResponse)
	err := c.cc.Invoke(ctx, Msg_ProposeDenomAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimDenomAdmin(ctx context.Context, in *MsgClaimDenomAdmin, opts ...grpc.CallOption) (*MsgClaimDenomAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgClaimDenomAdminResponse)
	err := c.cc.Invoke(ctx, Msg_ClaimDenomAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableDenomAdmin(ctx context.Context, in *MsgDisableDenomAdmin, opts ...grpc.CallOption) (*MsgDisableDenomAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDisableDenomAdminResponse)
	err := c.cc.Invoke(ctx, Msg_DisableDenomAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// Create token
	CreateDenom(context.Context, *MsgCreateDenom) (*MsgCreateDenomResponse, error)
	// Set the metadata of a denom
	SetDenomMetadata(context.Context, *MsgSetDenomMetadata) (*MsgSetDenomMetadataResponse, error)
	// UpdateDenomURI updates the URI of a denom and its sha256 hash, only bank
	// admin can do it.
	UpdateDenomURI(context.Context, *MsgUpdateDenomURI) (*MsgUpdateDenomURIResponse, error)
	// UpdateDenomMintingCap updates the minting cap and options o lock minting
	// cap changes on a denom, only bank admin can do it.
	UpdateDenomMintingCap(context.Context, *MsgUpdateDenomMintingCap) (*MsgUpdateDenomMintingCapResponse, error)
	// UpdateDenomMetadataAuth updates the metadata admin of a denom, needed for
	// case when bank admin is disabled
	UpdateDenomMetadataAuth(context.Context, *MsgUpdateDenomMetadataAuth) (*MsgUpdateDenomMetadataAuthResponse, error)
	// Mint and send tokens to a recipient
	MintAndSendTokens(context.Context, *MsgMintAndSendTokens) (*MsgMintAndSendTokensResponse, error)
	// BurnTokens - Burn tokens from the signer's account, signer has to be bank
	// admin to do it.
	BurnTokens(context.Context, *MsgBurnTokens) (*MsgBurnTokensResponse, error)
	WithdrawModuleFees(context.Context, *MsgWithdrawModuleFees) (*MsgWithdrawModuleFeesResponse, error)
	// ProposeDenomAdmin represents a message to propose a new denom admin
	ProposeDenomAdmin(context.Context, *MsgProposeDenomAdmin) (*MsgProposeDenomAdminResponse, error)
	// ClaimDenomAdmin represents a message to claim the denom admin role
	ClaimDenomAdmin(context.Context, *MsgClaimDenomAdmin) (*MsgClaimDenomAdminResponse, error)
	// DisableDenomAdmin represents a message to disable the denom admin role
	DisableDenomAdmin(context.Context, *MsgDisableDenomAdmin) (*MsgDisableDenomAdminResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateDenom(context.Context, *MsgCreateDenom) (*MsgCreateDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDenom not implemented")
}
func (UnimplementedMsgServer) SetDenomMetadata(context.Context, *MsgSetDenomMetadata) (*MsgSetDenomMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDenomMetadata not implemented")
}
func (UnimplementedMsgServer) UpdateDenomURI(context.Context, *MsgUpdateDenomURI) (*MsgUpdateDenomURIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDenomURI not implemented")
}
func (UnimplementedMsgServer) UpdateDenomMintingCap(context.Context, *MsgUpdateDenomMintingCap) (*MsgUpdateDenomMintingCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDenomMintingCap not implemented")
}
func (UnimplementedMsgServer) UpdateDenomMetadataAuth(context.Context, *MsgUpdateDenomMetadataAuth) (*MsgUpdateDenomMetadataAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDenomMetadataAuth not implemented")
}
func (UnimplementedMsgServer) MintAndSendTokens(context.Context, *MsgMintAndSendTokens) (*MsgMintAndSendTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintAndSendTokens not implemented")
}
func (UnimplementedMsgServer) BurnTokens(context.Context, *MsgBurnTokens) (*MsgBurnTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnTokens not implemented")
}
func (UnimplementedMsgServer) WithdrawModuleFees(context.Context, *MsgWithdrawModuleFees) (*MsgWithdrawModuleFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawModuleFees not implemented")
}
func (UnimplementedMsgServer) ProposeDenomAdmin(context.Context, *MsgProposeDenomAdmin) (*MsgProposeDenomAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeDenomAdmin not implemented")
}
func (UnimplementedMsgServer) ClaimDenomAdmin(context.Context, *MsgClaimDenomAdmin) (*MsgClaimDenomAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimDenomAdmin not implemented")
}
func (UnimplementedMsgServer) DisableDenomAdmin(context.Context, *MsgDisableDenomAdmin) (*MsgDisableDenomAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableDenomAdmin not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDenom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateDenom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDenom(ctx, req.(*MsgCreateDenom))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetDenomMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetDenomMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetDenomMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetDenomMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetDenomMetadata(ctx, req.(*MsgSetDenomMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDenomURI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDenomURI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDenomURI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateDenomURI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDenomURI(ctx, req.(*MsgUpdateDenomURI))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDenomMintingCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDenomMintingCap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDenomMintingCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateDenomMintingCap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDenomMintingCap(ctx, req.(*MsgUpdateDenomMintingCap))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDenomMetadataAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDenomMetadataAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDenomMetadataAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateDenomMetadataAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDenomMetadataAuth(ctx, req.(*MsgUpdateDenomMetadataAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintAndSendTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintAndSendTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintAndSendTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MintAndSendTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintAndSendTokens(ctx, req.(*MsgMintAndSendTokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurnTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_BurnTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnTokens(ctx, req.(*MsgBurnTokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawModuleFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawModuleFees)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawModuleFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_WithdrawModuleFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawModuleFees(ctx, req.(*MsgWithdrawModuleFees))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProposeDenomAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeDenomAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeDenomAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ProposeDenomAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeDenomAdmin(ctx, req.(*MsgProposeDenomAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimDenomAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimDenomAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimDenomAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClaimDenomAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimDenomAdmin(ctx, req.(*MsgClaimDenomAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableDenomAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableDenomAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableDenomAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DisableDenomAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableDenomAdmin(ctx, req.(*MsgDisableDenomAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zigchain.factory.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateDenom",
			Handler:    _Msg_CreateDenom_Handler,
		},
		{
			MethodName: "SetDenomMetadata",
			Handler:    _Msg_SetDenomMetadata_Handler,
		},
		{
			MethodName: "UpdateDenomURI",
			Handler:    _Msg_UpdateDenomURI_Handler,
		},
		{
			MethodName: "UpdateDenomMintingCap",
			Handler:    _Msg_UpdateDenomMintingCap_Handler,
		},
		{
			MethodName: "UpdateDenomMetadataAuth",
			Handler:    _Msg_UpdateDenomMetadataAuth_Handler,
		},
		{
			MethodName: "MintAndSendTokens",
			Handler:    _Msg_MintAndSendTokens_Handler,
		},
		{
			MethodName: "BurnTokens",
			Handler:    _Msg_BurnTokens_Handler,
		},
		{
			MethodName: "WithdrawModuleFees",
			Handler:    _Msg_WithdrawModuleFees_Handler,
		},
		{
			MethodName: "ProposeDenomAdmin",
			Handler:    _Msg_ProposeDenomAdmin_Handler,
		},
		{
			MethodName: "ClaimDenomAdmin",
			Handler:    _Msg_ClaimDenomAdmin_Handler,
		},
		{
			MethodName: "DisableDenomAdmin",
			Handler:    _Msg_DisableDenomAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zigchain/factory/tx.proto",
}
