// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zigchain/dex/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// newPoolFeePct is the percentage of the fee default on new pool
	NewPoolFeePct uint32 `protobuf:"varint,1,opt,name=new_pool_fee_pct,json=newPoolFeePct,proto3" json:"new_pool_fee_pct,omitempty"`
	// creationFee is the fee to create a new pool
	CreationFee uint32 `protobuf:"varint,2,opt,name=creation_fee,json=creationFee,proto3" json:"creation_fee,omitempty"`
	// beneficiary is the address that receives the fee to create a new factory
	Beneficiary string `protobuf:"bytes,3,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	// minimalLiquidityLock is the minimum amount of LP tokens that are locked in
	// the module account
	MinimalLiquidityLock uint32 `protobuf:"varint,4,opt,name=minimal_liquidity_lock,json=minimalLiquidityLock,proto3" json:"minimal_liquidity_lock,omitempty"`
	// maxSlippage is the maximum allowed slippage percentage for liquidity
	// deposits (in basis points, 1 = 0.01%)
	MaxSlippage uint32 `protobuf:"varint,5,opt,name=max_slippage,json=maxSlippage,proto3" json:"max_slippage,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_244560bdd7b0edb1, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetNewPoolFeePct() uint32 {
	if m != nil {
		return m.NewPoolFeePct
	}
	return 0
}

func (m *Params) GetCreationFee() uint32 {
	if m != nil {
		return m.CreationFee
	}
	return 0
}

func (m *Params) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *Params) GetMinimalLiquidityLock() uint32 {
	if m != nil {
		return m.MinimalLiquidityLock
	}
	return 0
}

func (m *Params) GetMaxSlippage() uint32 {
	if m != nil {
		return m.MaxSlippage
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "zigchain.dex.Params")
}

func init() { proto.RegisterFile("zigchain/dex/params.proto", fileDescriptor_244560bdd7b0edb1) }

var fileDescriptor_244560bdd7b0edb1 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xac, 0xca, 0x4c, 0x4f,
	0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0x49, 0xad, 0xd0, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x81, 0x49, 0xe9, 0xa5, 0xa4, 0x56, 0x48, 0x09, 0x26,
	0xe6, 0x66, 0xe6, 0xe5, 0xeb, 0x83, 0x49, 0x88, 0x02, 0x29, 0x91, 0xf4, 0xfc, 0xf4, 0x7c, 0x30,
	0x53, 0x1f, 0xc4, 0x82, 0x88, 0x2a, 0xbd, 0x67, 0xe4, 0x62, 0x0b, 0x00, 0x9b, 0x23, 0xa4, 0xce,
	0x25, 0x90, 0x97, 0x5a, 0x1e, 0x5f, 0x90, 0x9f, 0x9f, 0x13, 0x9f, 0x96, 0x9a, 0x1a, 0x5f, 0x90,
	0x5c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1b, 0xc4, 0x9b, 0x97, 0x5a, 0x1e, 0x90, 0x9f, 0x9f,
	0xe3, 0x96, 0x9a, 0x1a, 0x90, 0x5c, 0x22, 0xa4, 0xc8, 0xc5, 0x93, 0x5c, 0x94, 0x9a, 0x58, 0x92,
	0x99, 0x9f, 0x07, 0x52, 0x28, 0xc1, 0x04, 0x56, 0xc4, 0x0d, 0x13, 0x73, 0x4b, 0x4d, 0x15, 0x52,
	0xe0, 0xe2, 0x4e, 0x4a, 0xcd, 0x4b, 0x4d, 0xcb, 0x4c, 0xce, 0x4c, 0x2c, 0xaa, 0x94, 0x60, 0x56,
	0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x16, 0x12, 0x32, 0xe1, 0x12, 0xcb, 0xcd, 0xcc, 0xcb, 0xcc, 0x4d,
	0xcc, 0x89, 0xcf, 0xc9, 0x2c, 0x2c, 0xcd, 0x4c, 0xc9, 0x2c, 0xa9, 0x8c, 0xcf, 0xc9, 0x4f, 0xce,
	0x96, 0x60, 0x01, 0x1b, 0x27, 0x02, 0x95, 0xf5, 0x81, 0x49, 0xfa, 0xe4, 0x27, 0x67, 0x83, 0xac,
	0xce, 0x4d, 0xac, 0x88, 0x2f, 0xce, 0xc9, 0x2c, 0x28, 0x48, 0x4c, 0x4f, 0x95, 0x60, 0x85, 0x58,
	0x9d, 0x9b, 0x58, 0x11, 0x0c, 0x15, 0xb2, 0x92, 0x7b, 0xb1, 0x40, 0x9e, 0xb1, 0xeb, 0xf9, 0x06,
	0x2d, 0x51, 0x78, 0x60, 0x55, 0x80, 0x83, 0x0b, 0xe2, 0x4d, 0x27, 0xbd, 0x13, 0x8f, 0xe4, 0x18,
	0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5,
	0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x12, 0x41, 0xd3, 0x50, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4,
	0x06, 0x0e, 0x28, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0x8c, 0xc9, 0xd3, 0x7c, 0x01,
	0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NewPoolFeePct != that1.NewPoolFeePct {
		return false
	}
	if this.CreationFee != that1.CreationFee {
		return false
	}
	if this.Beneficiary != that1.Beneficiary {
		return false
	}
	if this.MinimalLiquidityLock != that1.MinimalLiquidityLock {
		return false
	}
	if this.MaxSlippage != that1.MaxSlippage {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxSlippage != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSlippage))
		i--
		dAtA[i] = 0x28
	}
	if m.MinimalLiquidityLock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinimalLiquidityLock))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CreationFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CreationFee))
		i--
		dAtA[i] = 0x10
	}
	if m.NewPoolFeePct != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NewPoolFeePct))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NewPoolFeePct != 0 {
		n += 1 + sovParams(uint64(m.NewPoolFeePct))
	}
	if m.CreationFee != 0 {
		n += 1 + sovParams(uint64(m.CreationFee))
	}
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MinimalLiquidityLock != 0 {
		n += 1 + sovParams(uint64(m.MinimalLiquidityLock))
	}
	if m.MaxSlippage != 0 {
		n += 1 + sovParams(uint64(m.MaxSlippage))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewPoolFeePct", wireType)
			}
			m.NewPoolFeePct = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewPoolFeePct |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationFee", wireType)
			}
			m.CreationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationFee |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimalLiquidityLock", wireType)
			}
			m.MinimalLiquidityLock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinimalLiquidityLock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSlippage", wireType)
			}
			m.MaxSlippage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSlippage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
