// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zigchain/dex/pool_uids.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PoolUids is secondary index on pools, allows for reverse lookup from pool
// date to pool id
type PoolUids struct {
	PoolUid string `protobuf:"bytes,1,opt,name=pool_uid,json=poolUid,proto3" json:"pool_uid,omitempty"`
	PoolId  string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (m *PoolUids) Reset()         { *m = PoolUids{} }
func (m *PoolUids) String() string { return proto.CompactTextString(m) }
func (*PoolUids) ProtoMessage()    {}
func (*PoolUids) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43c8fd5d6ddcb66, []int{0}
}
func (m *PoolUids) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolUids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolUids.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolUids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolUids.Merge(m, src)
}
func (m *PoolUids) XXX_Size() int {
	return m.Size()
}
func (m *PoolUids) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolUids.DiscardUnknown(m)
}

var xxx_messageInfo_PoolUids proto.InternalMessageInfo

func (m *PoolUids) GetPoolUid() string {
	if m != nil {
		return m.PoolUid
	}
	return ""
}

func (m *PoolUids) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func init() {
	proto.RegisterType((*PoolUids)(nil), "zigchain.dex.PoolUids")
}

func init() { proto.RegisterFile("zigchain/dex/pool_uids.proto", fileDescriptor_d43c8fd5d6ddcb66) }

var fileDescriptor_d43c8fd5d6ddcb66 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xa9, 0xca, 0x4c, 0x4f,
	0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0x49, 0xad, 0xd0, 0x2f, 0xc8, 0xcf, 0xcf, 0x89, 0x2f, 0xcd,
	0x4c, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x81, 0xc9, 0xea, 0xa5, 0xa4, 0x56,
	0x28, 0xd9, 0x71, 0x71, 0x04, 0xe4, 0xe7, 0xe7, 0x84, 0x66, 0xa6, 0x14, 0x0b, 0x49, 0x72, 0x71,
	0xc0, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0x17, 0x40, 0xe4, 0x84, 0xc4, 0xb9,
	0xc0, 0xcc, 0xf8, 0xcc, 0x14, 0x09, 0x26, 0xb0, 0x0c, 0x1b, 0x88, 0xeb, 0x99, 0xe2, 0xa4, 0x77,
	0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7,
	0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x22, 0x70, 0x57, 0x54, 0x80, 0xdd,
	0x51, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x76, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x84, 0x72, 0x9d, 0x05, 0xa4, 0x00, 0x00, 0x00,
}

func (m *PoolUids) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolUids) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolUids) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintPoolUids(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolUid) > 0 {
		i -= len(m.PoolUid)
		copy(dAtA[i:], m.PoolUid)
		i = encodeVarintPoolUids(dAtA, i, uint64(len(m.PoolUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoolUids(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolUids(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoolUids) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolUid)
	if l > 0 {
		n += 1 + l + sovPoolUids(uint64(l))
	}
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovPoolUids(uint64(l))
	}
	return n
}

func sovPoolUids(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolUids(x uint64) (n int) {
	return sovPoolUids(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoolUids) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolUids
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolUids: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolUids: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolUids
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolUids
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolUids
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolUids
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolUids
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolUids
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolUids(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolUids
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolUids(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolUids
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolUids
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolUids
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolUids
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolUids
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolUids
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolUids        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolUids          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolUids = fmt.Errorf("proto: unexpected end of group")
)
