// Code generated by MockGen. DO NOT EDIT.
// Source: x/tokenwrapper/module/module.go
//
// Generated by this command:
//
//	mockgen -source=x/tokenwrapper/module/module.go -package mock -destination x/tokenwrapper/testutil/mock/types_module_module.go
//

// Package mock is a generated GoMock package.
package mock
